#pragma once

// Early reverse engineering of emitter: https://users.csc.calpoly.edu/~zwood/teaching/csc572/final11/rsomers/
// Test app for stereo viewing: https://github.com/bobsomers/3dvgl/tree/master
// Best example of emitter programming (Linux): https://sourceforge.net/p/libnvstusb/code/HEAD/tree/
// Conversion to Windows and GitHub: https://github.com/FlintEastwood/3DVisionActivator
// Original mtbs3d thread about hacking emitter: http://www.mtbs3d.com/phpBB/viewtopic.php?f=26&t=3130
// Best list of 3D Vision certified monitors: https://www.mtbs3d.com/phpbb/viewtopic.php?t=23314
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// License from original project. This is has been heavily modified but uses
// a lot of the earlier code, especially the USB routines.
//
// https://github.com/FlintEastwood/3DVisionActivator
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "shutterGlasses.h"

#include <windows.h>
#include <string>
#include <vector>

#include "nvapi.h"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class NvidiaShutterGlasses : public ShutterGlasses
{
public:
    NvidiaShutterGlasses();
    ~NvidiaShutterGlasses();

    void WakeEmitter();
    void InitEmitter();
    void ClearEmitter();

    void ToggleEyes();
    void SetLeftEye();
    void SetRightEye();

    NvAPI_Status GetCurrentResolution();
    NvAPI_Status EnableLightBoost();
    NvAPI_Status DisableLightBoost();

private:
    struct monitor_info
    {
        std::string monitor_name;
        std::string monitor_EDID;
        float       refresh_rate;
        float       timer_x_us;
        float       timer_y_us;
        float       timer_z_us;
        float       timer_w_us;
    };
    std::vector<monitor_info> monitors;

    HANDLE pipe_usb_init  = INVALID_HANDLE_VALUE;
    HANDLE pipe_usb_swaps = INVALID_HANDLE_VALUE;

    NvU32 PrimaryDisplayID = 0xDEADBEEF;
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
